url: https://ramel-espol.github.io
baseurl: /webpage/

# Site settings
title: RAMEL
email: fryumbla@espol.edu.ec
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Luis Andrade
  pic: luis
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/luis-alberto-andrade-proa%C3%B1o-b6217a138

- name: César Aulestia
  pic: cesarAulestia
  position: Quadruped Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/c%C3%A9sar-alexander-aulestia-tena-089196264/
    - title: github
      url: https://github.com/caulesti
    - title: instagram
      url: https://www.instagram.com/aulestia82/

- name: Javier Pagalo
  pic: javierPagalo
  position: Robot Manipulation
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/javier-pagalo

- name: Ginger García
  pic: gingerGarcia
  position: Vision Recognition
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/ginger-garcia-58a0aa210

- name: Kevin Santana
  pic: kevinSantana
  position: UAV
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/kevin-santana-7a8211217/

- name: César Quintuña
  pic: cesarQuintuña
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-quintu%C3%B1a/

- name: Diego Ronquillo
  pic: diegoRonquillo
  position: Multi-Robot System
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/diego-ronquillo-a7b145175

- name: Náger Naranjo
  pic: nagerNaranjo
  position: Soft Robotics
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/n%C3%A1ger-rafael-naranjo-molina-b35a06231/

- name: Jonathan Zavala
  pic: jonathanZavala
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jonathan-zavala-%C3%A1vila-28b0b6210/

- name: Iesus Dávila
  pic: iesusDavila
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/mwlite/in/iesus-davila-aguilar-3054b61b0
    - title: github
      url: https://github.com/iesusdavila
    - title: instagram
      url: https://www.instagram.com/iesusdavilaa/

- name: Carlos González
  pic: carlosGonzalez
  position: Manipulator Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carlos-gonzalez-40237b17b/

- name: Daniela Cueva
  pic: danielaCueva
  position: Soft Robotic
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/daniela-cueva-jim%C3%A9nez-583348216

- name: Ramses García
  pic: ramsesGarcia
  position: Soft Robotic
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ramses-ian-garcia-galarza-514b851b6

- name: Aldahir Ramirez
  pic: aldahirRamirez
  position: Vision Recognition
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/aldahir-sebastian-ramirez-celi-4722a9233

- name: Cristobal Lara
  pic: cristobalLara
  position: Manipulator Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/crist%C3%B3bal-lara-3a7ba91b3

- name: Luis Arroba
  pic: luisArroba
  position: UAV
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/luis-mario-arroba-v%C3%A1squez-744974210/

- name: Axcel Espinoza
  pic: axcelEspinoza
  position: UGV
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/axcelespinoza
    - title: github
      url: https://github.com/Axcel17

- name: Favia Elizalde
  pic: faviaElizalde
  position: UAV
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/favia-elizalde-aristeguieta

- name: Oscar Yturralde
  pic: oscarYturralde
  position: UAV
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/oscar-yturralde-villegas-a50156216/

- name: Anthonny Piguave
  pic: anthonnyPiguave
  position: Multi-Robot System
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/anthonnypiguave/

- name: Anthony López
  pic: anthonyLopez
  position: Manipulator Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/anthony-l%C3%B3pez-uquillas-360208210

- name: José Landívar
  pic: joseLandivar
  position: Soft robotics
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jlandivar

- name: Aarón Villacis
  pic: aaronVillacis
  position: Soft Robotics
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/aaroneduardovillacisarroyave/

- name: Alanis Menéndez
  pic: alanisMenendez
  position: Soft Robotics
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/alanis-men%C3%A9ndez-san-lucas-2a703b210

- name: Andrew Tomalá
  pic: andrewTomala
  position: Soft Robotics
  social: 
  - title: linkedin
    url: https://www.linkedin.com/in/andrew-tomal%C3%A1-zapata-238989277/

# Alumni names, titles and social links
alumni:
- name: Yandri Uchuari
  pic: yandriUchuari
  position: Robots Design
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/yandriuchuari/

- name: Rhandall Valdez
  pic: rhandallValdez
  position: Robots Design
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rhandall-kevin-valdez-yepez/

- name: Jose Morán
  pic: joseMoran
  position: Machine Design
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/jose-antonio-mor%C3%A1n-rodriguez/

- name: Sofia Espana
  pic: sofiaEspana
  position: Computer Vision
  social: 
  - title: linkedin
    url: #

- name: Hugo Aviles 
  pic: hugoAviles
  position: Machine Design
  social: 
  - title: linkedin
    url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RAMEL-ESPOL
  - title: youtube
    url: https://www.youtube.com/channel/UCKUpIfFA_JDt5FEH6SxWQsA
  - title: linkedin
    url: https://www.linkedin.com/in/franciscoyumbla/
  - title: twitter
    url: http://twitter.com/franciscoyumbla
  - title: facebook
    url: https://www.facebook.com/FRANCISCOYUMBLA/

# Postal address (add as many lines as necessary)
address:
  - line: Escuela Superior Politécnica del Litoral
  - line: Facultad de Ingeniería en Mecánica y Ciencias de la Producción
  - line: Campus "Gustavo Galindo" Km. 30.5 Vía Perimetral


# Build settings
markdown: kramdown
permalink: pretty