url: https://ramel-espol.github.io
baseurl: /webpage/

# Site settings
title: RAMEL
email: fryumbla@espol.edu.ec
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Rhandall Valdez
  pic: rhandall
  position: Robot Design
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Yandri Uchuari
  pic: yandri
  position: Robot Design
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Jose Moran
  pic: Jose
  position: Machine Desing
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Luis Andrade
  pic: luis
  position: UGVr
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Cesar Aulestia
  pic: cesar
  position: Quadruped Design
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Javier Pagalo
  pic: javier
  position: Robot Manipulation
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RAMEL-ESPOL
  - title: youtube
    url: https://www.youtube.com/channel/UCKUpIfFA_JDt5FEH6SxWQsA
  - title: linkedin
    url: https://www.linkedin.com/in/franciscoyumbla/
  - title: twitter
    url: http://twitter.com/franciscoyumbla
  - title: facebook
    url: https://www.facebook.com/FRANCISCOYUMBLA/

# Postal address (add as many lines as necessary)
address:
  - line: Escuela Superior Politécnica del Litoral
  - line: Facultad de Ingeniería en Mecánica y Ciencias de la Producción
  - line: Campus "Gustavo Galindo" Km. 30.5 Vía Perimetral


# Build settings
markdown: kramdown
permalink: pretty