url: https://ramel-espol.github.io
baseurl: /webpage/

# Site settings
title: RAMEL
email: fryumbla@espol.edu.ec
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
- name: Rhandall Valdez
  pic: rhandall
  position: Robot Design
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Yandri Uchuari
  pic: yandri
  position: Robot Design
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Luis Andrade
  pic: luis
  position: UGV
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: César Aulestia
  pic: cesarAulestia
  position: Quadruped Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/c%C3%A9sar-alexander-aulestia-tena-089196264/
    - title: github
      url: https://github.com/caulesti
    - title: instagram
      url: https://www.instagram.com/aulestia82/

- name: Javier Pagalo
  pic: javier
  position: Robot Manipulation
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Sofia Espana
  pic: sofia
  position: Computer Vision
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Hugo Aviles
  pic: hugoAviles
  position: Machine Desing
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Jose Moran
  pic: jose
  position: Machine Desing
  social:
    - title: linkedin
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Iesus Dávila
  pic: iesusDavila
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/mwlite/in/iesus-davila-aguilar-3054b61b0
    - title: github
      url: https://github.com/iesusdavila
    - title: instagram
      url: https://www.instagram.com/iesusdavilaa/

- name: Carlos González
  pic: carlosGonzalez
  position: Manuoukators robotic arms
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carlos-gonzalez-40237b17b/
    - title: github
      url: #
    - title: instagram
      url: #

- name: Jonathan Zavala
  pic: jonathanZavala
  position: UGV
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jonathan-zavala-%C3%A1vila-28b0b6210/
    - title: github
      url: #.
    - title: instagram
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RAMEL-ESPOL
  - title: youtube
    url: https://www.youtube.com/channel/UCKUpIfFA_JDt5FEH6SxWQsA
  - title: linkedin
    url: https://www.linkedin.com/in/franciscoyumbla/
  - title: twitter
    url: http://twitter.com/franciscoyumbla
  - title: facebook
    url: https://www.facebook.com/FRANCISCOYUMBLA/

# Postal address (add as many lines as necessary)
address:
  - line: Escuela Superior Politécnica del Litoral
  - line: Facultad de Ingeniería en Mecánica y Ciencias de la Producción
  - line: Campus "Gustavo Galindo" Km. 30.5 Vía Perimetral


# Build settings
markdown: kramdown
permalink: pretty