url: https://ramel.tech
# url: https://ramel-espol.github.io

#baseurl: /webpage/

# Site settings
title: RAMEL
email: fryumbla@espol.edu.ec
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:

- name: Ing. Iesus Dávila
  pic: iesusDavila
  position: Investigador - CEDIA
  social:
    - title: linkedin
      url: https://www.linkedin.com/mwlite/in/iesus-davila-aguilar-3054b61b0

- name: Ing. Camila Reyes
  pic: camilaReyes
  position: Maestrante - Robots Programmer
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/camila-dom%C3%A9nica-reyes-vera-3b9aa8298/

- name: Ing. Isaac León
  pic: isaacLeon
  position: Maestrante - Robots Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/isaac-león-valdivieso-02a8662a2/?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app

- name: Náger Naranjo
  pic: nagerNaranjo
  position: Manipulator Design
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/n%C3%A1ger-rafael-naranjo-molina-b35a06231/

- name: Melissa Barberán
  pic: melissaBarberan
  position: Robots Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/melissa-barber%C3%A1n-gallardo-bb8248221/

- name: Newton Toledo
  pic: newtonToledo
  position: Computer Vision
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/newton-toledo-barreto-686447221/

- name: Pablo Lara
  pic: pabloLara
  position: Robots Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/pablo-lara-p/

- name: Lorelene Serrano
  pic: loreleneSerrano
  position: Robots Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/lorelene-serrano-395ba2277/

- name: Eliezer Acebo
  pic: eliezerAcebo
  position: Robots Design
  social: 
    - title: linkedin
      url: http://www.linkedin.com/in/eliezer-andr%C3%A9s-acebo-mota-321008363

- name: Ivan Baldeon
  pic: ivanBaldeon
  position: Robots Design
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/ivan-baldeon-baque-49035a2b4/

- name: Arturo Carrera
  pic: arturoCarrera
  position: Research Assistant
  social: 
    - title: linkedin
      url: http://www.linkedin.com/in/arturo-carrera-943873221


# Alumni names, titles and social links
alumni:
- name: Yandri Uchuari
  pic: yandriUchuari
  position: 2022II
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/yandriuchuari/

- name: Rhandall Valdez
  pic: rhandall
  position: 2022II
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/rhandall-kevin-valdez-yepez/

- name: Jose Morán
  pic: joseMoran
  position: 2022II
  social:
  - title: linkedin
    url: https://www.linkedin.com/in/jose-antonio-mor%C3%A1n-rodriguez/

- name: Hugo Aviles 
  pic: hugoAviles
  position: 2022II
  social: 
  - title: linkedin
    url: https://www.linkedin.com/in/hugmavil/

- name: Juan Sanchez
  pic: juan
  position: 2022II
  social: 
  - title: linkedin
    url: https://www.linkedin.com/in/juasesan/

- name: Sofía España
  pic: sofiaEspana
  position: 2022II
  social: 
  - title: linkedin
    url: https://www.linkedin.com/in/sof%C3%ADa-espa%C3%B1a-71743b1b6/

- name: Anthonny Piguave
  pic: anthonnyPiguave
  position: 2023I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/anthonnypiguave/

- name: Luis Andrade
  pic: luis
  position: 2023I
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/luis-alberto-andrade-proa%C3%B1o-b6217a138
      
- name: Javier Pagalo
  pic: javierPagalo
  position: 2023I
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/javier-pagalo

- name: Cristobal Lara
  pic: cristobalLara
  position: 2023I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/crist%C3%B3bal-lara-3a7ba91b3    

- name: Diego Ronquillo
  pic: diegoRonquillo
  position: 2023I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/diego-ronquillo-a7b145175


- name: José Landívar
  pic: joseLandivar
  position: 2023II
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/jlandivar

- name: César Quintuña
  pic: cesarQuintuña
  position: 2024I
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/cesar-quintu%C3%B1a/

- name: Iesus Dávila
  pic: iesusDavila
  position: 2024I
  social:
    - title: linkedin
      url: https://www.linkedin.com/mwlite/in/iesus-davila-aguilar-3054b61b0

- name: Luis Arroba
  pic: luisArroba
  position: 2024I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/luis-mario-arroba-v%C3%A1squez-744974210/

- name: Favia Elizalde
  pic: faviaElizalde
  position: 2024I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/favia-elizalde-aristeguieta

- name: Jorge Zapata
  pic: jorgeZapata
  position: 2024I
  social: 
   - title: linkedin
     url: #

- name: Sergio Balcázar
  pic: sergioBalcazar
  position: 2024I
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/sergio-javier-balc%C3%A1zar-mart%C3%ADnez-55a961224/

- name: César Aulestia
  pic: cesarAulestia
  position: 2024II
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/c%C3%A9sar-alexander-aulestia-tena-089196264/
    - title: github
      url: https://github.com/caulesti
    # - title: instagram
    #   url: https://www.instagram.com/aulestia82/

- name: Carlos González
  pic: carlosGonzalez
  position: 2024II
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/carlos-gonzalez-40237b17b/

- name: Martín Mendoza
  pic: martinMendoza
  position: 2024II
  social: 
  - title: linkedin
    url: https://www.linkedin.com/in/martin-mendoza-mansilla/

- name: Julio Dender
  pic: julioDender
  position: 2024II
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/julio-c%C3%A9sar-dender-aguilar-03778425b/

- name: Juan Saeteros
  pic: juanSaeteros
  position: 2024II
  social: 
    - title: linkedin
      url: https://www.linkedin.com/in/juan-marcos-saeteros-macias-b8a862231?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

- name: Erick Mendoza
  pic: erickMendoza
  position: 2024II
  social: 
    - title: linkedin
      url: http://www.linkedin.com/in/erick-mendoza-macias



# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/RAMEL-ESPOL
  - title: youtube
    url: https://www.youtube.com/channel/UCKUpIfFA_JDt5FEH6SxWQsA
  - title: linkedin
    url: https://www.linkedin.com/in/franciscoyumbla/
  - title: twitter
    url: https://twitter.com/franciscoyumbla
  - title: facebook
    url: https://www.facebook.com/FRANCISCOYUMBLA/

# Postal address (add as many lines as necessary)
address:
  - line: Escuela Superior Politécnica del Litoral
  - line: Facultad de Ingeniería en Mecánica y Ciencias de la Producción
  - line: Campus "Gustavo Galindo" Km. 30.5 Vía Perimetral


# Build settings
markdown: kramdown
permalink: pretty
